#!/bin/bash

. config

sudo apt-get -y install curl build-essential

bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)

sudo apt-get -y install couchdb

echo "rabbitmq-server rabbitmq-server/upgrade_previous note" | sudo debconf-set-selections

sudo apt-get install -y rabbitmq-server

sudo rabbitmqctl add_vhost /chef
sudo rabbitmqctl add_user chef testing
sudo rabbitmqctl set_permissions -p /chef chef ".*" ".*" ".*"

cd /tmp/
wget https://raw.github.com/flexiondotorg/oab-java6/master/oab-java6.sh -O oab-java6.sh
chmod +x oab-java6.sh 
sudo ./oab-java6.sh
sudo apt-get -y --force-yes install sun-java6-jre

sudo apt-get -y install zlib1g-dev libxml2-dev

echo "deb http://apt.opscode.com/ `lsb_release -cs`-0.10 main" | sudo tee /etc/apt/sources.list.d/opscode.list
sudo mkdir -p /etc/apt/trusted.gpg.d
gpg --keyserver keys.gnupg.net --recv-keys 83EF826A
gpg --export packages@opscode.com | sudo tee /etc/apt/trusted.gpg.d/opscode-keyring.gpg > /dev/null
sudo apt-get -y update
sudo apt-get -y install opscode-keyring
sudo apt-get -y install libgecode-dev

. ~/.rvm/scripts/rvm
rvm pkg install zlib
rvm pkg install openssl
rvm install 1.9.2
rvm use 1.9.2 --default
rvmsudo gem install chef-server chef-server-api chef-server chef-solr --no-ri --no-rdoc
rvmsudo gem install chef-server-webui --no-ri --no-rdoc

sudo mkdir /etc/chef

[ ${WEBUI_PASSWORD} ] || WEBUI_PASSWORD='password'
[ ${SERVERNAME} ] || SERVERNAME=`ip -f inet -o addr | grep eth0 | tr -s ' ' ' ' | cut -d ' ' -f 4 | cut -d '/' -f 1`

cat files/server.rb | sed "s:SERVERNAME:${SERVERNAME}:" | sed "s:PASSWORD:${WEBUI_PASSWORD}:" | sudo tee /etc/chef/server.rb > /dev/null

rvmsudo chef-solr-installer

[ ${CHEF_SERVER_USER} ] || CHEF_SERVER_USER=`whoami`
pushd files/upstart
for file in `ls`
do
  cat ${file} | sed "s:USER:${CHEF_SERVER_USER}:" |sudo tee /etc/init/${file} > /dev/null
done

popd

sudo apt-get install -y nginx
sudo cp files/nginx/vhost /etc/nginx/sites-available/chef
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/chef /etc/nginx/sites-enabled/default
sudo service nginx restart

echo "################################################################################"
echo
echo "Done"
echo

echo "Chef-server is at http://${SERVERNAME}:4000"
echo "Chef WebUI is at http://${SERVERNAME}"
echo
